export const SelectedDrillConstants = {
	SET_SELECTED_DRILL: "SET_SELECTED_DRILL",
	RESET_SELECTED_DRILL: "RESET_SELECTED_DRILL",
	EDIT_TASK: "EDIT_TASK",
	EDIT_COORDINATES: "EDIT_COORDINATES",
	ADD_DRILL_ATTACHMENT: "ADD_DRILL_ATTACHMENT",
	DELETE_DRILL_ATTACHMENT: "DELETE_DRILL_ATTACHMENT",
	EDIT_DRILL_ATTACHMENT: "EDIT_DRILL_ATTACHMENT"
};
