export const AllStatusConstants = {
	UPDATE_STATUSES: "UPDATE_STATUSES",
	SET_ALL_STATUSES: "SET_ALL_STATUSES",
	SET_ROLES_FILTERS: "SET_ROLES_FILTERS",
	ADD_ROLE_FILTER: "ADD_ROLE_FILTER",
	DELETE_ROLE_FILTER: "DELETE_ROLE_FILTER",
	RESET_ROLE_FILTER: "RESET_ROLE_FILTER",
	CLEAR_ROLE_FILTER: "CLEAR_ROLE_FILTER"
};
