export const DiagramEditorConstants = {
	SET_LINK_STYLE: "SET_LINK_STYLE",
	SET_LINK_SMOOTHNESS: "SET_LINK_SMOOTHNESS",
	SET_SELECTED_TASK_TEMPLATE: "SET_SELECTED_TASK_TEMPLATE",
	SET_SELECTED_TEMPLATE: "SET_SELECTED_TEMPLATE",
	RESET_SELECTED_TASK_TEMPLATE: "RESET_SELECTED_TASK_TEMPLATE",
	ADDED_ROLE_TO_TEMPLATE: "ADDED_ROLE_TO_TEMPLATE",
	ADDED_TASK_TO_TEMPLATE: "ADDED_TASK_TO_TEMPLATE",
	DELETED_ROLE_FROM_TEMPLATE: "DELETED_ROLE_FROM_TEMPLATE",
	EDITED_TASK_COORDINATES_TEMPLATE: "EDITED_TASK_COORDINATES_TEMPLATE",
	EDITED_TASK_DESCRIPTION_TEMPLATE: "EDITED_TASK_DESCRIPTION_TEMPLATE",
	EDITED_ROLE_COORDINATES_TEMPLATE: "EDITED_ROLE_COORDINATES_TEMPLATE",
	UNDO_LAST_TEMPLATE_EDIT: "UNDO_LAST_TEMPLATE_EDIT",
	REDO_LAST_TEMPLATE_EDIT: "REDO_LAST_TEMPLATE_EDIT",
	CLEAR_ALL_FROM_TEMPLATE: "CLEAR_ALL_FROM_TEMPLATE",
	OPEN_NEW_TEMPLATE: "OPEN_NEW_TEMPLATE"
};
