export const AllDrillsConstants = {
	UPDATE_DRILLS: "UPDATE_DRILLS",
	PENDING_UPDATE_ACTIVE_DRILLS: "PENDING_UPDATE_ACTIVE_DRILLS",
	UPDATE_ACTIVE_DRILLS: "UPDATE_ACTIVE_DRILLS",
	REVERT_ACTIVE_DRILL_ORDER: "REVERT_ACTIVE_DRILL_ORDER",
	PENDING_UPDATE_COMPLETED_DRILLS: "PENDING_UPDATE_COMPLETED_DRILLS",
	UPDATE_COMPLETED_DRILLS: "UPDATE_COMPLETED_DRILLS",
	REVERT_COMPLETED_DRILL_ORDER: "REVERT_COMPLETED_DRILL_ORDER"
};
