export const TasksConstants = {
	ADD_TASKS: "ADD_TASKS",
	RESET_ACTIVE_TASKS: "RESET_ACTIVE_TASKS",
	ADD_ACTIVE_TASK: "ADD_ACTIVE_TASK",
	REMOVE_ACTIVE_TASK: "REMOVE_ACTIVE_TASK", //when a task is completed, shift the leading object from active task array
	GET_NEXT_ACTIVE_TASK: "GET_NEXT_ACTIVE_TASK",
	SET_SELECTED_TASK: "SET_SELECTED_TASK",
	RESET_SELECTED_TASK: "RESET_SELECTED_TASK",
	EDIT_SELECTED_TASK_NOTES: "EDIT_SELECTED_TASK_NOTES",
	ADD_TASK_ATTACHMENT: "ADD_TASK_ATTACHMENT",
	DELETE_TASK_ATTACHMENT: "DELETE_TASK_ATTACHMENT",
	MAX_ACTIVE_TASKS: 5
};
